//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnhPhatMVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnhPhatMVC.Resources.Main", typeof(Main).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh Mục.
        /// </summary>
        public static string DANHMUC {
            get {
                return ResourceManager.GetString("DANHMUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dịch Vụ.
        /// </summary>
        public static string DICHVU {
            get {
                return ResourceManager.GetString("DICHVU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới Thiệu.
        /// </summary>
        public static string GIOITHIEU {
            get {
                return ResourceManager.GetString("GIOITHIEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỗ Trợ Trực Tuyến.
        /// </summary>
        public static string HOTROTRUCTUYEN {
            get {
                return ResourceManager.GetString("HOTROTRUCTUYEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết Nối Với Chúng Tôi.
        /// </summary>
        public static string KETNOIVOICHUNGTOI {
            get {
                return ResourceManager.GetString("KETNOIVOICHUNGTOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách Hàng.
        /// </summary>
        public static string KHACHHANG {
            get {
                return ResourceManager.GetString("KHACHHANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khuyến Mãi.
        /// </summary>
        public static string KHUYENMAI {
            get {
                return ResourceManager.GetString("KHUYENMAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên Hệ.
        /// </summary>
        public static string LIENHE {
            get {
                return ResourceManager.GetString("LIENHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản Phẩm.
        /// </summary>
        public static string SANPHAM {
            get {
                return ResourceManager.GetString("SANPHAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản Phẩm Mới Nhất.
        /// </summary>
        public static string SANPHAMMOINHAT {
            get {
                return ResourceManager.GetString("SANPHAMMOINHAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản Phẩm Nổi Bật.
        /// </summary>
        public static string SANPHAMNOIBAT {
            get {
                return ResourceManager.GetString("SANPHAMNOIBAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thương Hiệu.
        /// </summary>
        public static string THUONGHIEU {
            get {
                return ResourceManager.GetString("THUONGHIEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin Tức.
        /// </summary>
        public static string TINTUC {
            get {
                return ResourceManager.GetString("TINTUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang Chủ.
        /// </summary>
        public static string TRANGCHU {
            get {
                return ResourceManager.GetString("TRANGCHU", resourceCulture);
            }
        }
    }
}
